services:
  orderflow:
    image: orderflow
    build:
      context: .
      dockerfile: OrderFlow/Dockerfile
    ports:
      - "8800:80"
    depends_on:
      - postgres
    container_name: orderflow.server
  
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "orderflow"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    container_name: orderflow.db

